title: Robotics quotes
author: Semini Danoja
email: kgsemini@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Robotics and other combinations will make the world pretty fantastic compared with today.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
